### ISSUE TITLE
Seq sink :)

### ISSUE THREAD

**Issue by lukeschafer** [structured-log/structured-log#1]

**Comment by Michael-DST** [comment]
FWIW, I have referenced this issue in [a blog post](http://blog.developers.win/2016/02/the-great-net-client-divide-a-simple-example-hopefully/) exploring the difficulty/friction encountered of having to use awesome .NET technology like Seq/Serilog and finding its equivalent JavaScript implementation.  [Any support towards addressing this very fundamental problem in our community](http://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/10027638-create-a-ubiquitous-net-client-application-develo) would be greatly appreciated.  Thank you for any consideration!

**Comment by nblumhardt** [comment]
Thanks for the input @Michael-DST!

Currently the .NET world is taking most of my energies personally, but if you're keen to tackle this on the JavaScript side let me know and I can help answer any questions/send pointers.

All the best,
Nick

**Comment by ashleydavis** [comment]
There's a HTTP sink here: https://github.com/structured-log/structured-log-http-sink

It's pretty simple. You might be able to adapt it to seq.

**Comment by Wedvich** [comment]
I know this one is pretty old, but I kinda needed it for a project today, so I built a plugin for it:
https://github.com/Wedvich/structured-log-seq-sink

Tested with Seq 3.x, but it should work with 2.x as well, as the raw event endpoint looks identical (http://docs.getseq.net/v2/docs/posting-raw-events vs http://docs.getseq.net/v3/docs/posting-raw-events)

**Comment by ashleydavis** [comment]
Awesome. @Wedvich are you interested in joining structured-log to help move it forward?

**Comment by Wedvich** [comment]
@ashleydavis Yep, in fact I'm already registered as a contributor! Even though it's outside of the core project, I guess this has been my first contribution so far. But I do want to participate more - just a matter of finding the time to do so!

**Comment by ashleydavis** [comment]
Ha so you are! I'm struggling to find the time as well. Hoping to get back to it one day.

**Comment by Wedvich** [comment]
Yep :)

Since a sink for this is available now, I'll close the issue.
