### ISSUE TITLE
Implementation of batching.

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#10]
I've been thinking how to go about the batching implementation for structured-log. My thoughts on this have evolved, I think the original proposal was slightly wrong and I have a potentially better way of doing this now.

My original plan was that batching would be implemented fundamentally in the core and that it would require configuration per-sink, for example:

	var httpSink = require('structured-log-http-sink'); 
	
	var log = structuredLog.configuration()
	    .writeTo(httpSink({
	        url: 'http://somelogreceiver',    	// Configuration for the custom sink.
	        batchSize: 1000,          			// Flush the queue every 1000 logs.
	        timeDuration: 3000,         		// Milliseconds to wait before flushing the queue.            
	    })
	    .createLogger();

I'm don't think this approach is right now, because it splits the batching and the configuration between core and user code. This by itself doesn't sound good.

Also part of the original plan was two types of sinks. Unbatchable sinks look like this:

	var myCustomSink = function (options) {
	    return {
	        emit: function (logEvent) {
	            //
	            // ... your custom log event processing goes here ...
	            //
	        }
	    };
	};  

Batched sinks look like this:

	var myCustomBatchedSink = function (options) {
	    return {
	        emitBatch: function (logEvents) {
	            //
	            // ... process the array of log events ...
	            //
	        }
	    };
	};

This isn't overly complicated, but it does make creating a sink slightly more difficult in that a user building a sink needs to make that decision.

If we can say that an array of log events is always passed through then we only need to consider a single type of sink:

	var myCustomSink = function (options) {
	    return {
	        emit: function (logEvents) {
	            //
	            // ... process the array of log events ...
	            //
	        }
	    };
	};

This is easier to explain to sink implementors and they have no choice to make.

Of course the downside: unbatched sinks will only ever get arrays with a single element.

The real benefit is that this opens the way to treat any sink as either batched or unbatched and move the batching configuration out of the actual sink.

The example from before:

	var httpSink = require('structured-log-http-sink'); 
	
	var log = structuredLog.configuration()
	    .writeTo(httpSink({
	        url: 'http://somelogreceiver',
	        batchSize: 1000,
	        timeDuration: 3000,            
	    })
	    .createLogger();

Can be remade to configure the batch in the pipeline:

	var httpSink = require('structured-log-http-sink'); 
	
	var log = structuredLog.configuration()
		.batch({
	        batchSize: 1000,
	        timeDuration: 3000,            
		})
	    .writeTo(httpSink({
	        url: 'http://somelogreceiver',
	    })
	    .createLogger();
 

Advantages of this approach:

- Batching configuration and sink configuration are separated making the pipeline easier to read and keeping concerns separate.
- The same batching configuration can be shared between multiple sinks.
- Batching should be much simpler to implement, it isn't embedded in the core (conceptually at least), it will be just another addition to the *pipeline* (although the pipeline will require refactoring for this to work.

**Comment by ashleydavis** [comment]
I've implemented a basic version of batching.

The implementation isn't great... it won't support the flush function for example. But I'm happy with it as a first pass because it integrates as described above with out touching any other code. It is just another function in pipeline. I haven't yet changed sinks to accept an array of log events... when I do that more wide spread changes will be necessary.

In this commit I get the basic batching online with a single unit test: 
https://github.com/codecapers/structured-log/commit/3004f37b325402aa3ee248d0db5717b967b0ab19

In a second commit I got the time-based flush working with a second unit test:
https://github.com/codecapers/structured-log/commit/a684dbdf6f340360e493345fd013be050ea0c9f1

If you are interested in influencing the direction of the batching please comment on these commits.

**Comment by nblumhardt** [comment]
Love the API design, +1 :-)

The pipeline changes are going to be interesting, here are a couple of thoughts that spring to mind, because I can't resist puzzles like this...

```js
var log = structuredLog.configuration()
    .writeTo(consoleSink())
    .batch({
        batchSize: 10,
        timeDuration: 200,            
    })
    .writeTo(seqSink({
        url: 'http://my-seq/prd',
    })
    .batch({
        batchSize: 1000,
        timeDuration: 3000,            
    })
    .writeTo(httpSink({
        url: 'http://somelogreceiver',
    })
    .createLogger();
```

Not likely to be useful in practice, but this one helps get me started thinking about the implementation - semantically, it seems like:

* events immediately reach the console sink
* batches of up to 10 events every 100 ms reach the Seq sink
* those batches flow through, and get grouped up into 1000 event/3 sec batches for the other HTTP sink

Matches what you'd expect?

**Comment by ashleydavis** [comment]
Yeah that sounds good. Each 'batch' command should reset the batching for subsequent sinks. The current implementation is too simple and won't support this, but the core is going to have to change quite a bit to support batching anyway.

**Comment by ashleydavis** [comment]
Prototype version of batch is now complete and in PR #19.

A more though overhaul is needed so that logs are actually passed through to sinks as a collection and to support the flush function. I'll be moving on with this now.

**Comment by ashleydavis** [comment]
Another step toward proper batching.... the pipeline and all sinks now accept arrays of logs rather than single logs. This means that any sink can potentially be a batched sink.

Check out commit 64abbe5b270fdfb577e5b07d8b746a2be80e6993

**Comment by ashleydavis** [comment]
The implementation of batching is finished with with PR #22.

**Comment by nblumhardt** [comment]
Sorry mate, should have been clearer on my part. I mean a _sink_ implementation that will flush successfully when part of a batched pipeline (even when other batches may already be in progress when the flush call is made). Cheers!

**Comment by ashleydavis** [comment]
All sinks should flush correctly. A batched sink is no different to a non-batched sink now.

**Comment by ashleydavis** [comment]
Although some of the sinks probably need to be optimized for batching.

**Comment by nblumhardt** [comment]
For a network-based sink like the HTTP one, `flush()` will need to wait for pending network requests - e.g.:

https://github.com/structured-log/structured-log-http-sink/blob/master/structured-log-http-sink.js#L93

It's a bit tricker still because requests may already be in flight when `flush()` is called. `end()` is much the same - a process shouldn't be torn down until all in-flight log events end up at their destination.

Apologies if I'm missing something again - bouncing along on a bus! :-) Cheers!

**Comment by ashleydavis** [comment]
Oh, I get it. I guess we'll have to pass a callback to the emit function.
Or it could return a promise. We still need to talk about how to integrate
promises.
