### ISSUE TITLE
The function version of enrich should not take the event as a parameter.

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#11]
Some of the unit tests demonstrate a enrich taking a function, eg:

    .enrich(function(evt) { evt.properties.isHappy = true; })

I don't think this is structured right way. I think it should look like this:

    .enrich(function() { 
         return { 
             isHappy: true
         };
    })

So we can still dynamically generate properties, but we expose the internal structure of the log event (allowing the function to directly mess with 'evt.properties').

Batching is going to be simpler if we don't pass every log event into the user-defined function.

Thoughts on this?

**Comment by nblumhardt** [comment]
I think you're right; the more esoteric uses of `enrich()` could be handled by `pipe()` anyway, so the advantage of the narrow API wins for me.

**Comment by ashleydavis** [comment]
The enrich function was modified to not take the event. This makes it more suitable to work with batching and exposes less internal details of structured log to the outside world. Included in PR #19
