### ISSUE TITLE
Is it ok to factor out the message template parsing to a separate file?

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#17]
Will it be ok to move the message parsing to a separate Javascript file? I don't think it will be impacted by the addition of batching and I'd like to remove it from from the core so that I know I'm concentrating my efforts on the code that will need to change.

Also what do you think about making a separate repo and packages for the message parsing? It could then be used independently of _structured-log_. 

For example I would like to make a custom exception that can accept Serilog formatted messages as the exception message. This makes it easier to transfer exceptions to the log once they are caught. I have already done this in C#, I use it for catching unhanded exceptions at the highest level and then copy them, along with correct formatting and properties, to the log.

**Comment by nblumhardt** [comment]
Separate file or package sounds good. Have you been following https://github.com/adamchester/MessageTemplates? Similar goal in C# :-)

**Comment by ashleydavis** [comment]
Great, for the moment I'll just get it into a separate file. Later on we can look at moving it to another package.

**Comment by ashleydavis** [comment]
I started to look at this but realised it is complicated by the module structure. If I move the message template code out to a *message template* module. How is it best to import that into the core module?

It it was just nodejs we could *require* it in. If it was just code in the browser we could just put `MessageTemplate` under the `structuredLog` global. However it looks like we are support AMD modules which complicates things.

Do you have any suggestions on how to move forward with this?

**Comment by ashleydavis** [comment]
I think I've finally found a good way around this issue.

I intend to use *browserify* to compile the bower package. This will allow me to restructure the core code as regular Nodejs modules. This will make it easier to extract various parts of the system to separate modules which will allow each module to be simpler.

**Comment by Wedvich** [comment]
Closing this issue now, as the separation exists in the current codebase.
