### ISSUE TITLE
Structured Message not rendering correctly

### ISSUE THREAD

**Issue by nickpresta** [structured-log/structured-log#26]
Hello,

Great project -- I've been looking for something like this for a while in JavaScript land. My primary use case is the browser (with a console sink, and a couple custom sinks).

However, I'm having trouble using the structured logging formatting:

```javascript
// In browser
>>> log.info("Processed {@Position} in {Elapsed:000} ms.", {Position: {Latitude: 25, Longitude: 134}, Elapsed: 34});
>>> [INF] Processed {"Position":{"Latitude":25,"Longitude":134},"Elapsed":34} in {Elapsed:000} ms.
```

I copied this example from the README, so I assumed it would work as expected. Am I missing something?

The same is true in the node REPL as well:

```javascript
// In node REPL
> const structuredLog = require('structured-log');
> const consoleSink = require('structured-log/console-sink');
> const log = structuredLog.configure().writeTo(consoleSink()).create();
> log.info("Processed {@Position} in {Elapsed:000} ms.", {Position: {Latitude: 25, Longitude: 134}, Elapsed: 34});
[INF] Processed {"Position":{"Latitude":25,"Longitude":134},"Elapsed":34} in {Elapsed:000} ms.
```

It is slightly better than you use positional arguments:

```javascript
> log.info("Processed {@Position} in {Elapsed:000} ms.", {Latitude: 25, Longitude: 134}, 34);
[INF] Processed {"Latitude":25,"Longitude":134} in {Elapsed:000} ms.
```

Any help is much appreciated.

Thanks.

**Comment by ashleydavis** [comment]
How do you expect it to work?

**Comment by nickpresta** [comment]
Hi Ashley,

I would expect `Elapsed` to be replaced with `34` in the message produced. I'm not complaining about the API, but about the rendered message that is produced.

For example:

```javascript
> log.info("Processed {@action} by {userName} in {elapsed} seconds", {
  action: {
    type: "foo",
    log: true
  },
  userName: "nick",
  elapsed: 34
});
[INF] Processed {"action":{"type":"foo","log":true},"userName":"nick","elapsed":34} by {userName} in {elapsed} seconds
```

It seems that the message interpolation isn't recognizing that a single "context" object is being passed in -- I would expect the keys inside the context object to be expanded in the message so that I would get:

```javascript
> const context = {
  action: {
    type: "foo",
    log: true
  },
  userName: "nick",
  elapsed: 34
};
> log.info("Processed {@action} by {userName} in {elapsed} seconds", context);
[INF] Processed {"action":{"type":"foo","log":true}} by nick in 34 seconds
```

Thanks for the response.

**Comment by IanYates** [comment]
The API is expecting multiple parameters, much like console.log and friends.  What you're asking for sounds quite smart actually but isn't, to the best of my knowledge, the way the library currently works.

In your example, the {@action} placeholder is for the first ... argument, then comes {userName} then {elapsed}.  You needn't create an object with those names in addition to the names you're already putting in to the structured log template string.

**Comment by nickpresta** [comment]
@IanYates thanks for the explanation. 

Perhaps I am misunderstanding but the first paragraph in https://github.com/structured-log/structured-log#structured-logging describe the behavior I'm looking for:

> All the logging functions accept a message template and a set of key/value properties

In addition to the message below:

> Properties can also be specified by positional parameters

Which lead me to believe both usages are valid.

Is this a mistake in the documentation, or an expectation of how a future implementation may work? I can submit a PR updating the documentation, and examples to show how it *actually* works.

**Comment by IanYates** [comment]
Ahh.  I could well be wrong :)  I'm still using a really old copy of this library which closely resembles how Serilog (similar concept in C#) works.

**Comment by ashleydavis** [comment]
I just realised that the example code doesn't even exercise this code. I'll update it the example so I can confirm how this works.

**Comment by ashleydavis** [comment]
The readme is indeed wrong.

This doesn't work:

 log.info("Processed {@Position} in {Elapsed:000} ms.", {
     Position: position,
     Elapsed: elapsedMs
 });

This should work: 

 log.info("Processed {@Position} in {Elapsed:000} ms.", position, elapsedMs);

This does work: 

 log.info("Processed {@Position} in {Elapsed} ms.", position, elapsedMs);

All three cases should work so we'll look at in time.

**Comment by ashleydavis** [comment]
Thinking about this some more the first case can't work. It would be painful to determine the difference between a hash for properties and just an object that is passed in as a positional parameter.

It can only work either as positional parameters or a hash, not both. 

Given that positional parameters already work and that is the way it works in Serilog C# it's probably best to stick with that and I'll update the readme accordingly.
