### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ProTip** [structured-log/structured-log#27]
Hello,

Are there plans for a new npm release? The current version doesn't have TRACE and doesn't seem to configure different levels for different sinks properly. Thanks!

**Comment by ashleydavis** [comment]
I'm hoping to start work on this again soon. Are you interested in getting involved?

**Comment by Wedvich** [comment]
@ashleydavis Don't mean to hijack anything, but I'd like to chip in if help is needed. I've fallen in love with Serilog after using it on all of my recent C# projects, so I was very happy to see a JavaScript counterpart! Are there any particular bits you'd like a hand with?

Areas I'm immediately interested in looking at are the build chain (splitting the code into multiple files and using a bundler such as Rollup or Browserify, as mentioned in #17), cleaning up the documentation, adding more examples, and migrating the source code to ES6. Would any of those be interesting?

**Comment by ProTip** [comment]
I am! I don't suppose though that you have any interest in migrating this over to TypeScript? :)

**Comment by ashleydavis** [comment]
Cheers guys. I've added you both as contributors. 

Some basic rules:

- Don't commit directly to the repo. Always fork, make your changes, submit a pull request then have _someone else_ approve your changes.

- Try to follow the coding style already in place. 

- Please do TDD and write unit- or integration- tests before adding new features.

- Ensure that existing unit tests pass after you make a change.

- Don't break backward compatibility.

- If possible, stick to small changes that are easily verified and approved.

- If you want to make large changes, first please open an issue describe the problem and your design/plan for the proposed solution. If we all agree then you can move forward with that change.


Everything you guys wants to add sounds cool, esp TypeScript.

Cheers
Ash

**Comment by nblumhardt** [comment]
That's awesome! Welcome @ProTip and @Wedvich :-)
