### ISSUE TITLE
TypeScript rewrite

### ISSUE THREAD

**Issue by Wedvich** [structured-log/structured-log#28]
As mentioned in #27, I've begun experimenting with a rewrite of the current codebase to ES6 in this fork: https://github.com/Wedvich/structured-log. Not just because ES6 is cool (it totally is, though!) - but because the modern JavaScript syntax lends itself better to writing a clean, modular library. As mentioned in #17, it can be difficult to change or replace individual parts when everything is clumped together in one file. Splitting the code into multiple files/modules makes each moving part easier to reason about, but it's still not very elegant in ES5. So splitting code + ES6 seems like a good, future-proof solution.

The main focus now is to get it as close as possible to the current implementation, and basically pulling out the different components into separate classes without trying to restructure or change the internals.

To make sure it runs correctly in non-ES6 environments, a transpiler is needed to transform the code to ES5. I'm planning to use [Babel](https://babeljs.io) for this, as it's well-known and supported. In addition, it makes sense to distribute a single file rather than the whole set of source files, so a bundler is also required. [Webpack](https://webpack.github.io) and [Browserify](http://browserify.org) are the most common options here, but I'm leaning towards [Rollup](http://rollupjs.org) here as it avoids a lot of the internal infrastructure gunk of Webpack, so it seems like a better fit for a small library like this one.

Some thoughts:
- Should Bower support still be a thing? It depends on how much effort it takes. The bundle doesn't care if it's Node or a browser, so if a bower.json file is all it takes, I don't see why not.
- I'd like to achieve more parity with Serilog when it comes to things like the log level names (`WARN`-> `Warning` etc.) and logging methods, to make the transition easy and predictable both ways.
- Since there's no concept of extension methods in JavaScript as of yet, enabling syntax such as `.writeTo.consoleSink()` creates more coupling and mutation of the components that should be avoided. Sticking to `.writeTo(consoleSink())` is cleaner and more predictable.

There are some breaking changes that will need to be mapped out along the way and documented in an upgrade guide, but I think that should be acceptable since structured-log is still in a 0.x version.

Thoughts? Ideas?

**Comment by ashleydavis** [comment]
An ES6 sounds awesome. ES5 support is necessary, but Babel sounds like a good way to do that.

I've used Browserify for packaging and have found it to be good for that.

Bower support is still necessary, we have a completely [separate repo](https://github.com/structured-log/structured-log-bower) for that and the build script generates that repo.

I'm not sure about parity with Serilog. Nick and I agreed that structured-log should _feel_ like it fits well with JavaScript and if that means leaving behind Serilog conventions that's ok.

You should start by making a README that explains/demonstrates how the ES6 version will work. That gives us something to talk about and agree on before you put significant effort into the coding.

**Comment by Wedvich** [comment]
Thanks for the quick feedback! I'll make sure to keep Bower support intact. As for Serilog parity, I'm okay with the rationale you provided - I just didn't know if it diverged out of coincidence or choice.

I've managed to string the rewritten pipeline together now, so it's looking promising in terms of getting a testable version up and running soon. I'm working on updating the README as well, both to document the potential changes from the current version, but also because some of the features that are documented today are out of sync with what's actually available in the published package.

On the plus side, the upgrade path is very simple so far - these are the only changes from the current API:

```js
...

.writeTo.consoleSink()      // no
.writeTo(consoleSink())     // no for bundled sinks, 3rd party sinks make their own choice
.writeTo(new ConsoleSink()) // yes

...

log('stuff');      // no, log is now an object instance
log.info('stuff'); // yes

...
```

On a different note: now that the files are getting split up more and I'm taking advantage of ES6 class inheritance, I've been able to skip a bunch of the internal type/parameter validation. However, I also see an opportunity to sprinkle some TypeScript on top, as TS currently supports all ES6 features and is able to compile modules targeted at both ES6 and ES5. It's not an all-or-nothing deal either, since TS is a superset on top of ES6; any valid ES6 code is valid TS code, so we can apply it selectively where it makes sense.

This could completely eliminate internal type checks and move any validation logic up to the publicly exposed API surface, as internal type inconsistencies would be caught at compile-time by the TS compiler, which is an awesome prospect.

@ProTip - you mentioned wanting to get TypeScript in here, what are your thoughts on this?

**Comment by ProTip** [comment]
Heya,

Yeah if enough people are pro TS for development I can't recommend it enough. It's surprising the issues it will catch before you even start adding types by just tracking what methods exist and how many parameters they take :)

On a small project I've been playing around with strict null checks in 2.0; this is pretty awesome stuff for finding edge cases where undefine/null isn't being checked for or you don't have the type checks you thought you had.

Here is a "trick" you can use to create a public interface that could potentially take in anything while having the compiler ensure checked values are passed into the internal calls:
```TS
class something { f17c00671dc54796b3979da5857a8cfa: boolean }

function publicCall(param: string | number | something) {
  if ( typeof(param) === "string" ) {
    internalStringCall(param)
  } else if ( typeof(param) === "string" ) {
    internalNumberCall(param)
  } else {
    # Compile error because param is boolean | something
    internalBooleanCall(param)
  }
}

function internalStringCall(param: string) {}
function internalNumberCall(param: number ) {}
function internalBooleanCall(param: boolean) {}
```

**Comment by nitro52** [comment]
@Wedvich i had a quick look to check your progress, i see all the tests pass. Does this represent your progress?

**Comment by Wedvich** [comment]
@nitro52 Yep, though I haven't written a full test suite so I'm not completely confident that everything works as it should yet. I've written tests module by module before implementing them. However, now that I've picked it apart into separate components and have a better understanding of what the pipeline looks like under the hood, I'd like to revisit my approach when I have a bit more time, potentially sprinkling some TypeScript on there now that TS 2.0 is out.

**Comment by Wedvich** [comment]
I've begun redoing the implementation TypeScript, inlcuding rebuilding the pipeline from the inside out using promises:

https://github.com/Wedvich/structured-log/tree/typescript

Still an early WIP with no comments, tests or proper API surface yet, but I'm happy with the results so far. Using promises does imply that a polyfill is required for environments that don't support them, but I think the infrastructural advantages and the cleaner implementation make it worth it.

I'm going to experiment with it a bit more and then try to map out the breaking changes from the live version, because there will be some.

**Comment by Wedvich** [comment]
This has now turned fully into a TypeScript rewrite rather than ES6. The base goal is still the same: to achieve as much parity with the current API surface as possible, and avoid breaking changes unless there are tangible benefits to breaking things. Current bucket list:

- [ ] Document usage
- [ ] Document upgrade path from previous versions
- [ ] Create unit test suite
- [ ] Write comments and technical documentation
- [ ] Full implementation of enrichers
- [ ] Full implementation of filters
- [ ] Create typings for external libraries
- [ ] Generate Bower package

**Comment by nblumhardt** [comment]
Interesting! Can't wait to check it out 👍

**Comment by Wedvich** [comment]
Closing this as it's now covered by PR #35.
