### ISSUE TITLE
json-console-sink missing

### ISSUE THREAD

**Issue by andymac4182** [structured-log/structured-log#29]
There is a reference to json-console-sink in the readme but I can't seem to find the files relating to this. 

Where would be the best place to look or should I write my own?

**Comment by ashleydavis** [comment]
This is the console sink file:

https://github.com/structured-log/structured-log/blob/dev/src/npm/console-sink.js

Are you using npm or bower?

With npm/nodejs you should be able to do this:

var structuredLog = require('structured-log');
var consoleSink = require('structured-log/console-sink');

var log = structuredLog.configure()
    .writeTo(consoleSink())
    .create();

**Comment by ashleydavis** [comment]
Sorry it hasn't been implemented yet. The README documents what we intended to do with this project but forward momentum stalled after the basics were working.

If you create a json-console-sink we'd love to include it in the repo!

**Comment by andymac4182** [comment]
@ashleydavis Thanks for that :) I will give it a go.
