### ISSUE TITLE
Implement BatchedSink wrapper/base class

### ISSUE THREAD

**Issue by michaelsync** [structured-log/structured-log#34]
I am trying to implement my own custom batch sink using emitBatch but I got this error `Error: Expected undefined to be a function.`

I tried searching the whole repo with emitBatch but the only place that I found is in ReadMe.md. 

**Edited**

I found that my custom sink will be batched as long as we have the batch config. 

```
.batch({
            batchSize: 1000,  // Flush the queue every 1000 logs.
            timeDuration: 3000,         // Milliseconds to wait before flushing the queue.            
        })
```

**Comment by nblumhardt** [comment]
Thanks for the follow-up Michael; I think a bit of documentation could be outdated here, if you get a chance to PR any notes all help is appreciated :-)

**Comment by Wedvich** [comment]
The batching feature has been removed in the new release. I see some value in it that could probably justify implementing it again, but... when will this be applicable to the core pipeline? It makes more sense to leave this responsibility to the sinks. @nblumhardt @ashleydavis thoughts?

**Comment by nblumhardt** [comment]
@Wedvich I'm also of the opinion we can move this out of the pipeline. Moving responsibility to the sinks has been a reasonable, but not optimal, strategy for Serilog - it makes it laborious to update all the sinks to take advantage of different/improved/fixed batching code.

What about shipping one or more batching policies as wrappers?

```
  .writeTo(new BatchedSink(100, new OtherSink()))
```

**Comment by Wedvich** [comment]
That's a very good solution, I like it! The `BatchedSink` class could also be extended by 3rd party sinks, which would allow for a more seamless solution for those who'd prefer that. Adding it to the list for the next release!
