### ISSUE TITLE
Allow passing an exceptionOrErrorObject to log.error

### ISSUE THREAD

**Issue by michael-wolfenden** [structured-log/structured-log#36]
According to the documentation, the following should be possible
`log.error(exceptionOrErrorObject, 'Something bad happened...');`

Looking at the source however, the `exceptionOrErrorObject` is instead treated as the `messageTemplate` and not passed along to any of the sinks.

**Comment by nblumhardt** [comment]
@Wedvich is this one of the issues caught via the TypeScript rewrite?

**Comment by Wedvich** [comment]
It is now: https://github.com/Wedvich/structured-log/commit/c63c99534f2791efb33891cf0f7226d25c107dcd :smiley:

@michael-wolfenden Sorry about the discrepancy in what's documented and what's actually in the code! Correcting the docs is a big part of what's been undergone in PR #35, which I'm hoping to merge into dev in a few days and then prep for a release not too long after that.

**Comment by michael-wolfenden** [comment]
@Wedvich I believe that passing an `exceptionOrErrorObject` should only be an option when logging an `error` or `fatal`

**Comment by michael-wolfenden** [comment]
@Wedvich Thanks for your speedy response!!!

Will the included sinks also need to be updated to output the error if it exists. For example writing it to the console in the `console-sink` or adding an `@x` property in the `compact-console-sink` (see https://github.com/serilog/serilog-formatting-compact)?

**Comment by Wedvich** [comment]
Yep, those would need to be updated. The new `ConsoleSink` implementation does this now (https://github.com/structured-log/structured-log/pull/35/commits/0b759c634007701ebedcc2dd264679a4983d27b4) - I haven't remade any of the other sinks yet though (like the `CompactConsoleSink`), but those would also need to be updated for this.

**Comment by Wedvich** [comment]
@michael-wolfenden Version 0.1.0 is out on NPM now, where it should be possible to pass an `Error` object as the first parameter. Could you have a look if it's doing what you expect it to now?

**Comment by michael-wolfenden** [comment]
@Wedvich Just checked it out now and its working perfectly!!!. The seq sink is amazing as well. Thanks for all your hard work, its much appreciated. Feel free to close this issue.
