### ISSUE TITLE
Publish new release to npm/bower

### ISSUE THREAD

**Issue by Wedvich** [structured-log/structured-log#38]
@ashleydavis I've created a new release version now, that can be published to both npm and bower (currently at commit https://github.com/structured-log/structured-log/commit/ac83d31d16f12d79d885be59c019e01776922e2e). Does this look okay and ready to release into the wild?

In that case, could you publish the new package versions? For npm, it's a regular publish. For bower however, the package should be changed to point to the main repository here. It's no longer necessary to maintain a separate package/repository - bower will just use the package.json file together with the tags on master to figure out what to release, so there's no extra build step included.

- [x] npm
- [x] bower

**Comment by ashleydavis** [comment]
Great work Martin! Sorry I haven't been keeping up with it.

Is it backward compatible? If not we need to make some notes on how people can upgrade.

Otherwise I'm happy to publish.

**Comment by Wedvich** [comment]
It's not fully backwards-compatible no, but I've added a migration guide to the release notes here: https://github.com/structured-log/structured-log/releases/tag/v0.1.0

**Comment by ashleydavis** [comment]
Good stuff. Npm will be easy. I'll have to see what I can do about bower.

**Comment by ashleydavis** [comment]
Can't seem to publish on npm. It looks like I need to install some build tools.

Output attached.
  
```
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> structured-log@0.1.0 prepublish C:\Projects\github\structured-log\structured-log
> npm run build


> structured-log@0.1.0 build C:\Projects\github\structured-log\structured-log
> npm run build-es5 && npm run build-es6


> structured-log@0.1.0 build-es5 C:\Projects\github\structured-log\structured-log
> rollup -c rollup.config.es5.js

'rollup' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AshleyDavis\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-es5"
npm ERR! node v4.5.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! structured-log@0.1.0 build-es5: `rollup -c rollup.config.es5.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the structured-log@0.1.0 build-es5 script 'rollup -c rollup.config.es5.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the structured-log package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c rollup.config.es5.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs structured-log
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls structured-log
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\github\structured-log\structured-log\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AshleyDavis\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.5.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! structured-log@0.1.0 build: `npm run build-es5 && npm run build-es6`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the structured-log@0.1.0 build script 'npm run build-es5 && npm run build-es6'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the structured-log package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-es5 && npm run build-es6
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs structured-log
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls structured-log
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\github\structured-log\structured-log\npm-debug.log

npm ERR! addLocal Could not install C:\Projects\github\structured-log\structured-log
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AshleyDavis\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v4.5.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! structured-log@0.1.0 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the structured-log@0.1.0 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the structured-log package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs structured-log
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls structured-log
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\github\structured-log\structured-log\npm-debug.log

```

**Comment by ashleydavis** [comment]
Any idea how to fix bower? I could unregister and register structure-log again, but that seems a bit clunky.

**Comment by Wedvich** [comment]
Ah yes, it uses Rollup.js to build the output bundle. The dependencies are listed in `package.json` though, so just running `npm i` before doing the `npm publish` again should do the trick!

However, there's no Node <= 4.x support yet, so you won't be able to run the tests or examples. I think Node 4.x at least should be supported, so I'll need to figure out a better way of doing this using polyfills. We should wait until that is in place before publishing, as there's no good reason not to - Node 4 is still in long-term support until 2018. I'll create a separate issue for this.

As for bower, I don't actually think there is an "un-clunky" way of doing it. Going forward, I think it would be cleaner to keep the bower package in this single repo, especially with how much bower is converging towards npm. So, by going the unregister -> register way, the new package could be used going forward, and then perhaps we could create a new bower package with the "legacy" versions? What do you think?

**Comment by nblumhardt** [comment]
Looks like the NPM blurb could use some updates:

> structured-log 
> (Development version). NodeJS structured logging framework based on Serilog.

Not really the dev version; supports node and the browser.

> A structured logging framework for Javascript. Based on Serilog.
> WARNING: structured-log is a work in progress and will change over time.

Probably fair to remove this warning now - it's still a new library, but probably not churning much more than anything else on NPM :-)

@Wedvich added you to NPM.

I wonder if we could also clean up/remove redundant packages from Bower?

![image](https://cloud.githubusercontent.com/assets/342712/22002041/85c38028-dc94-11e6-8255-42dc8e2952d4.png)

Hmmm, just discovered you still were missing some permissions @Wedvich  - I've added them (via the Reviewers team) now.

HTH!

**Comment by Wedvich** [comment]
Yep, the NPM description is automatically pulled from the README when we publish a new version, so it will be updated with the same information as the main GitHub page when that's done. I'll have a look tonight!

I'll remove the `structured-log-alpha` package; it was mainly to test the the Bower publishing process for myself, since I don't have access to the other two pacakges.

We should remove te `structured-log-dev` too, though. If we need to publish a dev version, we can use a semver prerelease tag, which will make it available under the main Bower package when explicitly asking for prerelease versions - if not, it will just use the latest release version. So there's no need to keep them separate.

@ashleydavis could you unregister the `-dev` Bower package, and re-register the main package? Then I'll get the npm publish done as well.

**Comment by Wedvich** [comment]
New version out on NPM, and I've unregistered the `structured-log-alpha` package. Let's hope I didn't hopelessly break everyone's production code now! 😅

**Comment by ashleydavis** [comment]
Awesome work @Wedvich 

I've unregistered the bower package. When you register the new bower package make sure that it starts at a version number later than old package so that people don't get confused.

Thanks for driving this forward.

**Comment by Wedvich** [comment]
Bower package released as well. It'll still work the same for people using the "old" package, and it will pick up the new semver tag (0.1.0) as the latest version. The "old" packages are still searchable; I'm assuming it's cached somewhere in Bower and that it'll correct itself eventually.
