### ISSUE TITLE
Verbose and Debug levels don't work for ConsoleSink in Node.js

### ISSUE THREAD

**Issue by charandas** [structured-log/structured-log#47]
After spending this morning, chasing down the code of this module, I was finally able to determine why `verbose` wasn't working, but `info` was, despite setting the `minLevel` correctly.

```
this.console = {
      error: (internalConsole && (internalConsole.error || internalConsole.log)) || stub,
      warn:  (internalConsole && (internalConsole.warn || internalConsole.log)) || stub,
      info:  (internalConsole && (internalConsole.info || internalConsole.log)) || stub,
      debug: (internalConsole && (internalConsole.debug || internalConsole.log)) || stub,
      log:   (internalConsole && internalConsole.log) || stub
    };
```

where `internalConsole` defaults to `console`. I am using this with nodejs.  The reason for that per this [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Console) is:

>Console.debug(): An alias for log() - starting with Chromium 58 this method is a no-op on Chromium browsers.

Could we set working defaults, so newcomers who may not care to setup ConsoleSink options at first are not discouraged from it not working?

Maybe something like:
```
constructor(options?: ConsoleSinkOptions) {
    this.options = options || {};
    const internalConsole = this.options.console || typeof console !== 'undefined' && console || null;
    const stub = function () { };
    this.console = {
      error: (internalConsole && (internalConsole.error || internalConsole.log)) || stub,
      warn:  (internalConsole && (internalConsole.warn || internalConsole.log)) || stub,
      info:  (internalConsole && (internalConsole.info || internalConsole.log)) || stub,
      debug: (internalConsole && (internalConsole === console ? internalConsole.log : internalConsole.debug)) || stub,
      log:   (internalConsole && internalConsole.log) || stub
    };
  }
```

**Comment by charandas** [comment]
or something as simple as:

```
  constructor(options?: ConsoleSinkOptions) {
    this.options = options || {};
    const internalConsole = this.options.console || typeof console !== 'undefined' && {
        error: console.error,
        warn: console.error,
        info: console.log,
        debug: console.error,
        log: console.log
      } || null;
   };
    const stub = function () { };
    this.console = {
      error: (internalConsole && (internalConsole.error || internalConsole.log)) || stub,
      warn:  (internalConsole && (internalConsole.warn || internalConsole.log)) || stub,
      info:  (internalConsole && (internalConsole.info || internalConsole.log)) || stub,
      debug: (internalConsole && (internalConsole.debug || internalConsole.log)) || stub,
      log:   (internalConsole && internalConsole.log) || stub
    };
  }
```

**Comment by Wedvich** [comment]
Hi @charandas! Thanks for figuring this out and reporting it. It appears that it has actually never existed on Node's `Console` object (https://nodejs.org/api/console.html) but that they've added a no-op stub since it was a common problem to get `console.debug is undefined` errors. I'll do a check for Node and wire the call to `console.log` instead in that case.

As a side note, `console.debug` still works in the Chrome browser (as of 61.0.3163.100), but the **Verbose** logging level is hidden by the the **Default** filter setting, which only includes the **Info**, **Warnings** and **Error** levels.

![Chrome console filters](https://images.imgbox.com/70/56/63paJirr_o.png)

**Comment by charandas** [comment]
Thanks @Wedvich for timely response.

**Comment by charandas** [comment]
@Wedvich the npm publish wasn't done for this release?

```
npm ERR! notarget No matching version found for structured-log@^0.2.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by Wedvich** [comment]
It was: https://www.npmjs.com/package/structured-log

When I run `npm i structured-log@^0.2.0` it succeeds for me. What version of npm/what npm repositories do you have set up?

**Comment by charandas** [comment]
Sorry about that. I am using nexus, and I have noticed that sometimes my private npm registry which proxies the main npm registry lies to me. I will re-run, and my guess is it will most certainly pass.
