### ISSUE TITLE
Potential change to logger configuration

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#5]
Should we change 'configuration' to 'configure'?

I think using a 'verb' sounds better.

So this:

	var log = structuredLog.configuration()
	    .writeTo(consoleSink())
	    .createLogger();

Would change to this:

	var log = structuredLog.configure()
	    .writeTo(consoleSink())
	    .createLogger();

**Comment by nblumhardt** [comment]
:+1:
