### ISSUE TITLE
Error in ConsoleSink

### ISSUE THREAD

**Issue by kvpt** [structured-log/structured-log#53]
Hi,

The commit 0877f7d2 seem to have introduced a regression.
I have this error in the browser (Chrome and Edge) at [this line](https://github.com/structured-log/structured-log/blob/dev/src/consoleSink.ts#L30).

> Cannot read property 'node' of undefined in the console sink.

If I provide the console in the console sink constructor the error disappear.

I specify that I use webpack and typescript.

**Comment by Wedvich** [comment]
Hmm, this sounds strange - it shouldn't get to that point unless you're actually on. Do you have a global named `process` in your code? What does the compiled code look like for that function in your browser?

**Comment by kvpt** [comment]
You right, my app is build with Vue Cli, and the process variable is populated with environment variables by the Vue Cli.
