### ISSUE TITLE
Another potential change to logger configuration

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#6]
I'm wondering if we should shorten 'createLogger' simple to 'create'.

So this:

	var log = structuredLog.configuration()
	    .writeTo(consoleSink())
	    .createLogger();

Would become this:

	var log = structuredLog.configuration()
	    .writeTo(consoleSink())
	    .create();

**Comment by nblumhardt** [comment]
Ambivalent on this one - happy either way. Less is more, perhaps :-)
