### ISSUE TITLE
posibility of funding and putting out a call for new maintainers? 

### ISSUE THREAD

**Issue by SimonCropp** [structured-log/structured-log#61]
So this is a pretty cool project. Have you considered starting an open collective? https://opencollective.com/ or some other funding model?

Also would it be a good idea to put out a call for some extra maintainers? perhaps @anderswestberg, @Gachapen or @Perroquiet would be interested?

**Comment by aaronpowell** [comment]
What kind of support is needed? Is it a financial thing? Is it that the current maintainers are no longer working in this space and it's deprioritised? Is it "done"?

**Comment by SimonCropp** [comment]
@aaronpowell seems like many legit issues are stalled.

**Comment by aaronpowell** [comment]
@SimonCropp I'd noticed that, which was why I was posing the question of what is the reason, not just the symptom :)

**Comment by SimonCropp** [comment]
@aaronpowell I would like to use this project. However there are some bugs i need fixed and some basic feature i would like to add. I am happy to do the PRs, or others in my current team, but if no one wants to be a maintainer....

**Comment by davisb10** [comment]
I have made a fork of this repository and have resolved most of the active issues. Please feel free to check it out. :) 
https://github.com/davisb10/serilogger
