### ISSUE TITLE
Another potential change to logger configuration

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#7]
Should 'minimumLevel' be changed to 'minLevel'?

Eg, this:

	var log = structuredLog.configuration()
		.minimumLevel('VERBOSE')
		.writeTo(consoleSink())
		.createLogger();

Becomes:

	var log = structuredLog.configuration()
		.minLevel('VERBOSE')
		.writeTo(consoleSink())
		.createLogger();

**Comment by nblumhardt** [comment]
Happy either way. Is there any precedent in other libs to go by?

I tend to avoid contractions where possible personally, but `min` is pretty much universal so no opinion here :-)

**Comment by ashleydavis** [comment]
I'm not sure about any precedent.

I feel the objective should be to minimize names (and still be meaningful) where possible. 

It's ok in C# when you have good intellisense to complete names for you. Javascript isn't usually that smart.

**Comment by nblumhardt** [comment]
:+1:
