### ISSUE TITLE
Addition of 'debug' logging level.

### ISSUE THREAD

**Issue by ashleydavis** [structured-log/structured-log#9]
A comment was left recently about having debug as a separate logging level.

I'd like to move forward with this.

Thoughts? Comments?

**Comment by IanYates** [comment]
That was me, so you've got one vote at least   :+1:

**Comment by nblumhardt** [comment]
Hi all - do you mean debug + trace, or debug + verbose, or debug + verbose + trace? It'd be nice to keep the set of levels somewhat constrained if possible.

Also, do you want to keep the Serilog debug > verbose, or go with the DNX verbose > debug?

I was a bit of a fan of the simplification, since though more levels are useful, I find there's just so much confusion around these levels it's kinda refreshing not to have to think about it ;-) ... but just my 0.02, if you guys are missing the two levels, no objections here.

**Comment by IanYates** [comment]
In my mind I equate "trace" and "verbose" - so Debug + Trace or Debug + Verbose (but not all three).  

Verbose/Trace: Everything including the kitchen sink finds its way into the logs.  For example, at this level, I log SignalR connected/disconnected - they're things that should work but if they're broken I need to see the detail.

Debug is something I can run a new installation at for a little while just to see how things are going on under the hood but not cause too much grief.

Info and above (below?) I see as Info, Warning, Error & Fatal...  I've bought into the Serilog / Seq ecosystem wholeheartedly :)

**Comment by nblumhardt** [comment]
Note this spun out of #8 (just mentioning here for traceability).

Guys, maybe you're right and this is a bikeshed not worth the time right now. I'd be happy if we line this up with Serilog, since I suspect many others will be coming from that background, too.

Can we then remove `trace` to keep things simple?

**Comment by ashleydavis** [comment]
I think I've already replaced trace with verbose.

Just to recap... current levels are verbose, info, warn & error.

In the future I intended to add debug... making for debug, verbose, info, warn and error.

**Comment by IanYates** [comment]
Wary of bikeshedding, but just to be clear, is the planned order actually verbose, debug, info, warn and error?  (ie verbose level will include everything, debug includes all except verbose events, and so on)

**Comment by ashleydavis** [comment]
I though the order would be:  debug, verbose, info, warn and error.

**Comment by IanYates** [comment]
(I really hate to be the stick in the mud - sorry)
That's not what Serilog/Seq do...  Not saying they're perfect, just that'll be mighty confusing if debug & verbose are swapped.

**Comment by ashleydavis** [comment]
Ok I didn't realize it worked that way. Probably not so useful to me then... I usually think of the debug level as the first level to go in production. And 'verbose' as being a special case of 'info'.

I can probably make do without the debug level anyway. Still, I'm happy if you want to implement it, otherwise let's close this issue.

**Comment by nblumhardt** [comment]
LOL :-) ... guess we three make a pretty good case study in the challenges of choosing "the levels below INFO".

When I first decided to give this problem the boot by cutting the number of levels, I thought about making the supported level either `DEBUG` or `VERBOSE` but worried it might be confusing for someone coming from Serilog to find one level but not the other, hence I settled on `TRACE`.

If that's unfamiliar and you guys think we're better off calling the level `DEBUG`, consistency with Serilog is probably worth maintaining. I can PR the inclusion of `VERBOSE` if that would fit.

**Comment by ashleydavis** [comment]
I'd prefer verbose. I basically want two levels of info. As far as I am concerned debug logging is separate and always gets turned off or stripped out in production anyway.

**Comment by nblumhardt** [comment]
Ah crap, my typo:

> I can PR the inclusion of VERBOSE if that would fit.

Should have read:

> I can PR the inclusion of DEBUG if that would fit.

Sigh :) getting to that time of the evening.

The PR is one option, lining up with the Serilog levels, not sure any more based on your comment above that this is what you're after. Will come to it with fresh eyes in the morning.

In any case, I think having `dev` in a consistent state is probably the priority for now, so happy however we get there.

Cheers!
